# Generated by Django 6.0.3 on 2026-04-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_discipline_program_type'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='course_classes', to='academics.discipline'),
        ),
    ]
