# Generated by Django 6.0.3 on 2026-04-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_courseclass_disciplines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='classsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
