# Generated by Django 6.0.3 on 2026-04-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_remove_classsession_time_slot_classsession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='end_time',
            field=models.TimeField(default='09:30'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='start_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
