# Generated by Django 6.0.3 on 2026-04-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_course_course_type'),
        ('scheduling', '0004_alter_classsession_end_time_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseclass',
            name='unique_course_per_term',
        ),
        migrations.AddField(
            model_name='courseclass',
            name='section',
            field=models.IntegerField(choices=[(1, 'Group 1'), (2, 'Group 2'), (3, 'Group 3'), (4, 'Group 4'), (5, 'Group 5'), (6, 'Group 6'), (7, 'Group 7'), (8, 'Group 8'), (9, 'Group 9'), (10, 'Group 10')], default=1, help_text='Select the group/section identifier for this class batch.'),
        ),
        migrations.AddConstraint(
            model_name='courseclass',
            constraint=models.UniqueConstraint(fields=('course', 'term', 'section'), name='unique_course_term_section'),
        ),
    ]
