# Generated by Django 6.0.3 on 2026-04-14 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_term_options_alter_course_title_and_more'),
        ('scheduling', '0005_remove_courseclass_unique_course_per_term_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('LAB', 'Lab'), ('TUTORIAL', 'Tutorial')], default='LECTURE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday')])),
                ('period', models.IntegerField(choices=[(1, '08:00 – 09:30'), (2, '09:45 – 11:15'), (3, '11:30 – 13:00'), (4, '13:30 – 15:00'), (5, '15:15 – 16:45')])),
            ],
            options={
                'ordering': ['day', 'period'],
            },
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='course_class',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='instructor',
        ),
        migrations.RemoveConstraint(
            model_name='courseclass',
            name='unique_course_term_section',
        ),
        migrations.AddField(
            model_name='session',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.courseclass'),
        ),
        migrations.AddField(
            model_name='session',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='academics.room'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('day', 'period'), name='unique_timeslot'),
        ),
        migrations.AddField(
            model_name='session',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='scheduling.timeslot'),
        ),
    ]
