# Generated by Django 6.0.3 on 2026-04-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_enrollment_lab_session_and_more'),
        ('scheduling', '0006_session_timeslot_remove_classsession_course_class_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassSession',
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='disciplines',
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='term',
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('room', 'timeslot'), name='unique_room_timeslot'),
        ),
        migrations.DeleteModel(
            name='CourseClass',
        ),
    ]
