# Generated by Django 6.0.3 on 2026-04-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_delete_classsession_remove_courseclass_coordinator_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='unique_room_timeslot',
        ),
    ]
