# Generated by Django 6.0.7 on 2026-08-03 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_course_department_and_more'),
        ('scheduling', '0008_remove_session_unique_room_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.room'),
        ),
        migrations.AlterField(
            model_name='session',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scheduling.timeslot'),
        ),
    ]
