# Generated by Django 6.0.7 on 2026-08-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_baseuser_managers_studentprofile_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
            ],
        ),
    ]
