# Generated by Django 6.0.3 on 2026-04-09 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='scheduling.courseclass')),
                ('lab_session', models.ForeignKey(blank=True, limit_choices_to={'session_type': 'LAB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_enrollments', to='scheduling.classsession')),
                ('lecture_session', models.ForeignKey(blank=True, limit_choices_to={'session_type': 'LECTURE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_enrollments', to='scheduling.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.studentprofile')),
                ('tutorial_session', models.ForeignKey(blank=True, limit_choices_to={'session_type': 'TUTORIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorial_enrollments', to='scheduling.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=4, help_text='Decimal weight, e.g. 0.30 for 30%', max_digits=5)),
                ('score', models.DecimalField(decimal_places=2, help_text='Score out of 100', max_digits=5)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='records.enrollment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course_class'), name='unique_student_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='gradeentry',
            constraint=models.UniqueConstraint(fields=('enrollment', 'component'), name='unique_grade_component_per_enrollment'),
        ),
    ]
