# Generated by Django 6.0.3 on 2026-04-14 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_enrollment_course_class'),
        ('scheduling', '0006_session_timeslot_remove_classsession_course_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='lab_session',
            field=models.ForeignKey(blank=True, limit_choices_to={'session_type': 'LAB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_enrollments', to='scheduling.session'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='lecture_session',
            field=models.ForeignKey(blank=True, limit_choices_to={'session_type': 'LECTURE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_enrollments', to='scheduling.session'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='tutorial_session',
            field=models.ForeignKey(blank=True, limit_choices_to={'session_type': 'TUTORIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorial_enrollments', to='scheduling.session'),
        ),
    ]
