# Generated by Django 6.0.3 on 2026-04-20 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_enrollment_lab_session_and_more'),
        ('scheduling', '0007_delete_classsession_remove_courseclass_coordinator_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week', models.PositiveSmallIntegerField(help_text='Week number within the term (1-based)')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='scheduling.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'session', 'week'), name='unique_attendance_per_session_week')],
            },
        ),
    ]
