# Generated by Django 6.0.3 on 2026-04-21 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_course_lab_sessions_course_lec_sessions_and_more'),
        ('records', '0004_attendancerecord'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeentry',
            name='weight',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='week',
            field=models.PositiveSmallIntegerField(help_text='Week number within the term (1-based).'),
        ),
        migrations.AlterField(
            model_name='gradeentry',
            name='component',
            field=models.CharField(help_text="e.g. 'Midterm Exam', 'Final Exam', 'Quiz 1', 'Homework'", max_length=100),
        ),
        migrations.AlterField(
            model_name='gradeentry',
            name='score',
            field=models.DecimalField(decimal_places=2, help_text="Raw score on this component's scale (not out of 100).", max_digits=5),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('HOMEWORK', 'Homework'), ('PROJECT', 'Project'), ('ESSAY', 'Essay')], max_length=20)),
                ('due_week', models.PositiveSmallIntegerField(help_text='Week number within the term by which the assignment is due (1-based).')),
                ('max_points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.courseclass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'Midterm Exam'), ('FINAL', 'Final Exam'), ('PRACTICAL', 'Practical/Lab Exam'), ('QUIZ', 'Quiz')], max_length=20)),
                ('week', models.PositiveSmallIntegerField(help_text='Week number within the term when the exam is held (1-based).')),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum achievable score, e.g. 30.00 for a midterm worth 30 marks.', max_digits=5)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.courseclass')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused'), ('CHEATING', 'Disqualified')], default='PRESENT', max_length=15)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='records.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='users.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='records.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.studentprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('exam_type__in', ['FINAL', 'MIDTERM'])), fields=('course_class', 'exam_type'), name='unique_singular_exam_type_per_class'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_student_exam_result'),
        ),
        migrations.AddConstraint(
            model_name='studentsubmission',
            constraint=models.UniqueConstraint(fields=('student', 'assignment'), name='unique_student_assignment_submission'),
        ),
    ]
