# Generated by Django 6.0.3 on 2026-07-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_assignment_deleted_at_assignment_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='is_active',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled (Active)'), ('DROPPED', 'Dropped (Early/Refunded)'), ('WITHDRAWN', 'Withdrawn (W on Transcript)'), ('COMPLETED', 'Completed (Final Grade Issued)')], default='ENROLLED', max_length=15),
        ),
    ]
