# Generated by Django 6.0.7 on 2026-07-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_remove_enrollment_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gradeentry',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='gradeentry',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='is_active',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_grade_points',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only calculated when enrollment is COMPLETED.', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='final_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Official final grade. Null until enrollment is COMPLETED.', max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='gradeentry',
            index=models.Index(fields=['enrollment', 'score'], name='idx_enrollment_score_cover'),
        ),
    ]
