# Generated by Django 6.0.7 on 2026-08-03 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_courseprerequisite_curriculumblueprint'),
        ('records', '0008_remove_assignment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.courseclass'),
        ),
    ]
