# Generated by Django 6.0.7 on 2026-08-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_alter_courseclass_coordinator_and_more'),
        ('records', '0009_alter_enrollment_course_class'),
        ('scheduling', '0009_alter_session_room_alter_session_timeslot'),
        ('users', '0002_alter_baseuser_managers_studentprofile_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_student_enrollment',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course_class'), include=('id',), name='unique_student_enrollment'),
        ),
    ]
