# Generated by Django 6.0.7 on 2026-08-07 08:14

import django.db.models.deletion
from django.db import migrations, models

# 1. ADD THIS FUNCTION to handle the data backfill
def populate_course_class(apps, schema_editor):
    ExamResult = apps.get_model('records', 'ExamResult')
    
    # Loop through all existing results, fetch the exam's course class, and save it
    for result in ExamResult.objects.select_related('exam').all():
        result.course_class_id = result.exam.course_class_id
        result.save(update_fields=['course_class_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_alter_courseclass_coordinator_and_more'),
        ('records', '0010_remove_enrollment_unique_student_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='course_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.courseclass'),
        ),
        # 2. ADD THIS OPERATION to execute the function
        migrations.RunPython(populate_course_class, reverse_code=migrations.RunPython.noop),
    ]