# Generated by Django 6.0.7 on 2026-09-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_courseclass_schedule_dirty'),
        ('records', '0012_enrollment_active_by_class_index'),
        ('scheduling', '0009_alter_session_room_alter_session_timeslot'),
        ('users', '0003_alter_baseuser_managers'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(condition=models.Q(('status', 'ENROLLED')), fields=['student'], name='enrollment_active_by_student_idx'),
        ),
    ]
