# Generated by Django 6.0.7 on 2026-09-19 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_enrollment_enrollment_active_by_student_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='enr_active_by_student_idx',
            old_name='enrollment_active_by_student_idx',
        ),
    ]
