from django.core.management.base import BaseCommand
from records.models import (
    Assignment,
    AttendanceRecord,
    Enrollment,
    Exam,
    ExamResult,
    StudentSubmission
)

class Command(BaseCommand):
    help = "Quickly audits and counts the records generated by the seed scripts."

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.HTTP_INFO("\n=== Database Seed Audit ==="))

        # Dictionary mapping the display name to the actual database count
        counts = {
            "Enrollments": Enrollment.objects.count(),
            "Assignments": Assignment.objects.count(),
            "Exams": Exam.objects.count(),
            "Student Submissions": StudentSubmission.objects.count(),
            "Exam Results": ExamResult.objects.count(),
            "Attendance Records": AttendanceRecord.objects.count(),
        }

        total_records = 0

        for label, count in counts.items():
            total_records += count
            
            # Format numbers with commas for readability (e.g., 10,000 instead of 10000)
            formatted_count = f"{count:,}"
            
            if count > 0:
                self.stdout.write(self.style.SUCCESS(f" {label:<20}: {formatted_count}"))
            else:
                self.stdout.write(self.style.WARNING(f" {label:<20}: {formatted_count} (Empty)"))

        self.stdout.write(self.style.HTTP_INFO("==========================="))
        self.stdout.write(self.style.SUCCESS(f" Total Tracked Records: {total_records:,}\n"))