import datetime 
from django.core.management.base import BaseCommand
from academics.models import Department, Discipline, Term, Course 

class Command(BaseCommand):
    help = 'Seeds departments, disciplines, terms, and courses for Alexandria University'

    def handle(self, *args, **kwargs):

        # ─── 16 Scientific Departments ────────────────────────────
        scientific_departments = [
            {"code": "EMP", "name": "Engineering Mathematics and Physics"},
            {"code": "ARC", "name": "Architectural Engineering"},
            {"code": "CVE", "name": "Civil Engineering"}, 
            {"code": "STR", "name": "Structural Engineering"},
            {"code": "IRH", "name": "Irrigation Engineering and Hydraulics"},
            {"code": "TRE", "name": "Transportation Engineering"},
            {"code": "SAN", "name": "Sanitary Engineering"},
            {"code": "MEC", "name": "Mechanical Engineering"},
            {"code": "EEC", "name": "Electrical Engineering - Communications"},
            {"code": "EEP", "name": "Electrical Engineering - Power"},
            {"code": "CHE", "name": "Chemical Engineering"},
            {"code": "TEE", "name": "Textile Engineering"},
            {"code": "NAM", "name": "Naval Architecture and Marine Engineering"},
            {"code": "MIE", "name": "Production Engineering"},
            {"code": "NRE", "name": "Nuclear and Radiation Engineering"},
            {"code": "CSE", "name": "Computer and Systems Engineering"},
        ]

        self.stdout.write("Creating 16 Scientific Departments...")
        for d in scientific_departments:
            Department.objects.get_or_create(code=d["code"], defaults={"name": d["name"]})
        self.stdout.write(self.style.SUCCESS(" 16 Scientific Departments loaded."))

        # ─── 12 SSP — inserted into BOTH Department and Discipline ─
        ssp_programs = [
            {"code": "MSE", "name": "Materials Science and Engineering"},
            {"code": "GPE", "name": "Gas and Petrochemicals Engineering"},
            {"code": "EME", "name": "Electromechanical Engineering"},
            {"code": "CCE", "name": "Computer and Communication Engineering"},
            {"code": "CAE", "name": "Architectural and Construction Engineering"},
            {"code": "OCE", "name": "Offshore and Coastal Engineering"},
            {"code": "BME", "name": "Biomedical Engineering"},
            {"code": "CEE", "name": "Civil and Environmental Engineering"},
            {"code": "MRE", "name": "Mechatronics and Robotics Engineering"},
            {"code": "MAE", "name": "Mechanical and Aerospace Engineering"},
            {"code": "EEN", "name": "Electronics Engineering with Nanotechnology"},
            {"code": "RSA", "name": "Resilient and Smart Architectural Engineering"},
        ]

        self.stdout.write("Creating 12 SSP Departments...")
        for p in ssp_programs:
            Department.objects.get_or_create(code=p["code"], defaults={"name": p["name"]})
        self.stdout.write(self.style.SUCCESS(" 12 SSP Departments loaded. Total: 28 Departments."))

        self.stdout.write("Creating 12 SSP Disciplines...")
        for p in ssp_programs:
            dept = Department.objects.get(code=p["code"])
            Discipline.objects.get_or_create(
                code=p["code"],
                defaults={
                    "name":         p["name"],
                    "program_type": "SSP", 
                    "department":   dept,
                }
            )
        self.stdout.write(self.style.SUCCESS(" 12 SSP Disciplines loaded."))

        # ─── 11 GSP Programs ──────────────────────────────────────
        gsp_programs = [
            {"code": "ARC", "name": "Architectural Engineering",                "dept": "ARC"},
            {"code": "CVE", "name": "Civil Engineering",                        "dept": "CVE"}, 
            {"code": "MEC", "name": "Mechanical Engineering",                   "dept": "MEC"},
            {"code": "EEC", "name": "Communications and Electronics Engineering", "dept": "EEC"},
            {"code": "EEP", "name": "Electrical Power and Machines Engineering",  "dept": "EEP"},
            {"code": "CHE", "name": "Chemical Engineering",                       "dept": "CHE"},
            {"code": "TEE", "name": "Textile Engineering",                        "dept": "TEE"},
            {"code": "NAM", "name": "Naval Architecture and Marine Engineering",  "dept": "NAM"},
            {"code": "MIE", "name": "Manufacturing and Industrial Engineering",   "dept": "MIE"},
            {"code": "NRE", "name": "Nuclear and Radiation Engineering",          "dept": "NRE"},
            {"code": "CSE", "name": "Computer and Systems Engineering",           "dept": "CSE"},
        ]

        self.stdout.write("Creating 11 GSP Disciplines...")
        for p in gsp_programs:
            dept = Department.objects.filter(code=p["dept"]).first() if p["dept"] else None
            Discipline.objects.get_or_create(
                code=p["code"] + "_GSP", 
                defaults={
                    "name":         p["name"],
                    "program_type": "GSP", 
                    "department":   dept,
                }
            )
        self.stdout.write(self.style.SUCCESS(" 11 GSP Disciplines loaded."))

        # =========================================================
        # ACADEMIC TERMS
        # =========================================================
        terms_data = [
            {"name": "Spring 2023", "start_date": datetime.date(2023, 2, 11), "end_date": datetime.date(2023, 6, 15), "is_active": False},
            {"name": "Fall 2023",   "start_date": datetime.date(2023, 9, 30), "end_date": datetime.date(2024, 1, 25), "is_active": False},
            {"name": "Spring 2024", "start_date": datetime.date(2024, 2, 10), "end_date": datetime.date(2024, 6, 15), "is_active": False},
            {"name": "Fall 2024",   "start_date": datetime.date(2024, 9, 28), "end_date": datetime.date(2025, 1, 23), "is_active": False},
            {"name": "Spring 2025", "start_date": datetime.date(2025, 2, 8),  "end_date": datetime.date(2025, 6, 15), "is_active": False},
            {"name": "Fall 2025",   "start_date": datetime.date(2025, 9, 27), "end_date": datetime.date(2026, 1, 22), "is_active": False},
            {"name": "Spring 2026", "start_date": datetime.date(2026, 2, 14), "end_date": datetime.date(2026, 6, 15), "is_active": True},
            {"name": "Fall 2026",   "start_date": datetime.date(2026, 9, 26), "end_date": datetime.date(2027, 1, 21), "is_active": False}
        ]

        self.stdout.write("Creating Academic Terms...")
        for term in terms_data:
            obj, created = Term.objects.get_or_create(
                name=term["name"],
                defaults={
                    "start_date": term["start_date"],
                    "end_date": term["end_date"],
                    "is_active": term["is_active"]
                }
            )
            if term["is_active"] and not obj.is_active:
                obj.is_active = True
                obj.save()
                
        self.stdout.write(self.style.SUCCESS(f" {len(terms_data)} Academic Terms loaded!"))

        # =========================================================
        # COURSES
        # =========================================================
        
        courses_data = [
            # ─── Screenshot 1 ─────────────────────────────────────────
            {"code": "STR 211", "title": "Structural Analysis -1", "credits": 3},
            {"code": "STR 212", "title": "Mechanics of Structures", "credits": 3},
            {"code": "STR 221", "title": "Properties and Testing of Materials – 1", "credits": 3},
            {"code": "STR 313", "title": "Structural Analysis -2", "credits": 3},
            {"code": "STR 222", "title": "Properties and Testing of Materials – 2", "credits": 3},
            {"code": "STR 231", "title": "Fundamentals of Reinforced Concrete", "credits": 3},
            {"code": "STR 341", "title": "Soil Mechanics", "credits": 3},
            {"code": "STR 331", "title": "Design of Reinforced Concrete Structures -1", "credits": 3},
            {"code": "STR 351", "title": "Design of Steel Structures-1", "credits": 3},
            {"code": "IRH 211", "title": "Fundamentals of Hydraulics", "credits": 3},
            {"code": "IRH 312", "title": "Open Channel Hydraulics", "credits": 3},
            {"code": "IRH 331", "title": "Irrigation and Drainage Engineering", "credits": 3},
            {"code": "TRE 211", "title": "Fundamentals of Surveying and Geomatics", "credits": 3},
            {"code": "TRE 212", "title": "Surveying and Topography – 1", "credits": 3},
            {"code": "TRE 221", "title": "Civil Drawing", "credits": 3},
            {"code": "TRE 231", "title": "Engineering Geology", "credits": 3},
            {"code": "TRE 313", "title": "Surveying and Topography – 2", "credits": 3},
            {"code": "TRE 341", "title": "Transportation Planning and Traffic Engineering", "credits": 3},
            {"code": "TRE 361", "title": "Highway Engineering", "credits": 3},

            # ─── Screenshot 2 ─────────────────────────────────────────
            {"code": "STR 433", "title": "Design of Reinforced Concrete Structures -2", "credits": 2},
            {"code": "STR 342", "title": "Foundation Engineering", "credits": 3},
            {"code": "STR 452", "title": "Design of Steel Structures-2", "credits": 3},
            {"code": "STR 461", "title": "Management of Construction Projects", "credits": 3},
            {"code": "IRH 432", "title": "Design of Water Crossing Structures and Weirs", "credits": 2},
            {"code": "IRH 414", "title": "Design of Hydraulic Structures", "credits": 2},
            {"code": "TRE 451", "title": "Harbor Engineering and Marine Structures", "credits": 3},
            {"code": "SAN 311", "title": "Sanitary Engineering", "credits": 3},
            {"code": "CVE 401", "title": "Graduation Project", "credits": 3},
            {"code": "CVE 3E1", "title": "Elective – 1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CVE 4E2", "title": "Elective – 2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CVE 4E3", "title": "Elective – 3", "credits": 2, "course_type": "ELECTIVE"},
            {"code": "CVE 4E4", "title": "Elective – 4", "credits": 2, "course_type": "ELECTIVE"},
            {"code": "CVE 4E5", "title": "Elective – 5", "credits": 2, "course_type": "ELECTIVE"},

            # ─── Screenshot 3 ─────────────────────────────────────────
            {"code": "MEC 211", "title": "Thermodynamics-1", "credits": 3},
            {"code": "MEC 212", "title": "Thermodynamics-2", "credits": 3},
            {"code": "MEC 232", "title": "Fundamentals of Fluid Mechanics", "credits": 2},
            {"code": "MEC 241", "title": "Mechanical Drawing-1", "credits": 3},
            {"code": "MEC 243", "title": "Mechanics of Materials", "credits": 3},
            {"code": "MEC 244", "title": "Strength of Materials", "credits": 2},
            {"code": "MEC 245", "title": "Dynamics of Rigid Bodies and Mechanisms", "credits": 3},
            {"code": "MEC 246", "title": "Mechanics of Machinery", "credits": 3},
            {"code": "EEP x82", "title": "Introduction to Electric Circuits and Electrical Machines", "credits": 3},
            {"code": "EEP x51", "title": "Introduction to Power Electronics", "credits": 3},
            {"code": "MIE x61", "title": "Basic Manufacturing Processes", "credits": 2},
            {"code": "MEC 311", "title": "Heat Transfer", "credits": 3},
            {"code": "MEC 321", "title": "Fundamentals of Combustion Engineering", "credits": 2},
            {"code": "MEC 331", "title": "Fluid Mechanics-1", "credits": 3},
            {"code": "MEC 341", "title": "Mechanical Design-1", "credits": 3},
            {"code": "MEC 343", "title": "Mechanical Vibrations", "credits": 3},
            {"code": "MEC 352", "title": "Applied Numerical Methods for Mechanical Engineering", "credits": 3},
            {"code": "MEC 412", "title": "Renewable Energy", "credits": 3},
            {"code": "MEC 422", "title": "Gas Dynamics", "credits": 3},
            {"code": "MEC 451", "title": "Mechanical Engineering Measurements", "credits": 3},

            # ─── Screenshot 4 ─────────────────────────────────────────
            {"code": "MEC 4E1", "title": "Elective - 1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MEC 4E2", "title": "Elective - 2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MEC 4E3", "title": "Elective - 3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MEC 4E4", "title": "Elective - 4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MEC 4E5", "title": "Elective - 5", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MEC 413", "title": "Design of Thermal Equipment", "credits": 3},
            {"code": "MEC 414", "title": "Refrigeration and Air Conditioning Equipment and Applications", "credits": 3},
            {"code": "MEC 415", "title": "Operation and Management of Thermal Power Plants", "credits": 3},
            {"code": "MEC 416", "title": "Water Desalination Technology", "credits": 3},
            {"code": "MEC 421", "title": "Gas Turbines in Aviation", "credits": 3},
            {"code": "MEC 423", "title": "Automotive and Autotronics Engineering", "credits": 3},
            {"code": "MEC 424", "title": "Alternative Fuels", "credits": 3},
            {"code": "MEC 426", "title": "Maintenance and Fault Diagnosis of Internal Combustion Engines", "credits": 3},
            {"code": "MEC 434", "title": "Turbomachinery", "credits": 3},
            {"code": "MEC 435", "title": "Microfluidics", "credits": 3},
            {"code": "MEC 436", "title": "Fluid Power Systems", "credits": 3},
            {"code": "MEC 438", "title": "Pumping Systems", "credits": 3},
            {"code": "MEC 443", "title": "Codes and Specifications of Mechanical Systems", "credits": 3},
            {"code": "MEC 444", "title": "Industrial Mechanisms", "credits": 3},
            {"code": "MEC 445", "title": "Maintenance Planning", "credits": 3},
            {"code": "MEC 446", "title": "Introduction to Mechatronic Systems", "credits": 3},

            # ─── Screenshot 5 ─────────────────────────────────────────
            {"code": "EEC 231", "title": "Electronic Circuits and Devices", "credits": 3},
            {"code": "EEC 241", "title": "Introduction to Logic Circuits & Computer Programming", "credits": 3},
            {"code": "EEC 271", "title": "Signals and Systems", "credits": 3},
            {"code": "EEC 281", "title": "Information Transmission Principles", "credits": 3},
            {"code": "EEC 311", "title": "Electrical Circuit Analysis", "credits": 3},
            {"code": "EEC 332", "title": "Solid State Electronics: Physics and Devices", "credits": 3},
            {"code": "EEC 333", "title": "Electronic Circuit Analysis", "credits": 3},
            {"code": "EEC 342", "title": "Logic Circuit Design", "credits": 3},
            {"code": "EEC 343", "title": "Microprocessors and Microcontrollers", "credits": 3},
            {"code": "EEC 361", "title": "Electromagnetic Fields", "credits": 3},
            {"code": "EEC 362", "title": "Waves and Propagation", "credits": 3},
            {"code": "EEC 371", "title": "Digital Signal Processing", "credits": 3},
            {"code": "EEC 381", "title": "Introduction to Communications", "credits": 3},
            {"code": "EEC 462", "title": "Microwave & Optical Transmission Media", "credits": 3},
            {"code": "EEP 211", "title": "Electric Circuits", "credits": 3},
            {"code": "EEP 212", "title": "Electrical and Electronic Measurements", "credits": 3},
            {"code": "EEP 271", "title": "Electric Power and Machines", "credits": 3},

            # ─── Screenshot 6 ─────────────────────────────────────────
            {"code": "EEC 334", "title": "Analog Integrated Circuits", "credits": 3},
            {"code": "EEC 382", "title": "Digital Communications", "credits": 3},
            {"code": "EEC 441", "title": "Embedded systems", "credits": 3},
            {"code": "EEC 471", "title": "Automatic Control Systems", "credits": 3},
            {"code": "EEC 481", "title": "Wireless Communications", "credits": 2},
            {"code": "EEC 401", "title": "Graduation Project-1", "credits": 2},
            {"code": "EEC 402", "title": "Graduation Project-2", "credits": 2},
            {"code": "EEC 3E1", "title": "Elective-1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EEC 4E1", "title": "Elective-2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EEC 4E2", "title": "Elective-3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EEC 4E3", "title": "Elective-4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EEC 4E4", "title": "Elective-5", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EEC 4E5", "title": "Elective-6", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EEC 4E6", "title": "Elective-7", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 7 ─────────────────────────────────────────
            {"code": "EEP 211", "title": "Electric Circuits", "credits": 3},
            {"code": "EEP 212", "title": "Electrical and Electronic Measurements", "credits": 3},
            {"code": "EEP 213", "title": "Electromagnetic Fields", "credits": 3},
            {"code": "EEP 214", "title": "Principles of Microprocessors", "credits": 3},
            {"code": "EEP 221", "title": "Introduction to Energy Systems", "credits": 3},
            {"code": "EEP 231", "title": "DC Machines and Power Transformers", "credits": 3},
            {"code": "EEP 311", "title": "Advanced Electric Circuits Analysis", "credits": 3},
            {"code": "EEP 312", "title": "Measurement Systems", "credits": 3},
            {"code": "EEP 321", "title": "Transmission and Distribution of Electric Power", "credits": 3},
            {"code": "EEP 322", "title": "Electric Power Equipment", "credits": 3},
            {"code": "EEP 341", "title": "Automatic Control and Computer Applications", "credits": 3},
            {"code": "EEP 351", "title": "Power Electronics-1", "credits": 3},
            {"code": "EEP 441", "title": "Automatic Control Theory", "credits": 3},
            {"code": "EEC 231", "title": "Electronic Circuits and Devices", "credits": 3},
            {"code": "EEC 241", "title": "Logic Circuits & Computer Programming", "credits": 3},
            {"code": "EEC 281", "title": "Information Transmission Principles", "credits": 3},
            {"code": "MEC 453", "title": "Thermodynamics and Fluid Mechanics", "credits": 2},
            {"code": "MEC 419", "title": "Thermal Power Plants", "credits": 2},

            # ─── Screenshot 8 ─────────────────────────────────────────
            {"code": "EEP 331", "title": "AC Machines", "credits": 3},
            {"code": "EEP 332", "title": "Electric Drives", "credits": 3},
            {"code": "EEP 352", "title": "Power Electronics-2", "credits": 3},
            {"code": "EEP 361", "title": "Protection of Electric Power Systems", "credits": 3},
            {"code": "EEP 421", "title": "Power Systems Analysis", "credits": 3},
            {"code": "EEP 422", "title": "High Voltage and its applications", "credits": 3},
            {"code": "EEP 451", "title": "Industrial Automation", "credits": 3},
            {"code": "EEP 401", "title": "Graduation Project 1", "credits": 3},
            {"code": "EEP 402", "title": "Graduation Project 2", "credits": 2},
            {"code": "EEP 4E1", "title": "Elective 1", "credits": 2, "course_type": "ELECTIVE"},
            {"code": "EEP 4E2", "title": "Elective 2", "credits": 2, "course_type": "ELECTIVE"},
            {"code": "EEP 4E3", "title": "Elective 3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EEP 4E4", "title": "Elective 4", "credits": 2, "course_type": "ELECTIVE"},
            {"code": "EEP 4E5", "title": "Elective 5", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EEP 4E6", "title": "Elective 6", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 9 ─────────────────────────────────────────
            {"code": "CHE 211", "title": "Organic Chemistry", "credits": 4},
            {"code": "CHE 212", "title": "Physical Chemistry", "credits": 3},
            {"code": "CHE 213", "title": "Analytical Chemistry and Instrumental Analysis", "credits": 3},
            {"code": "CHE 222", "title": "Materials Science and Engineering", "credits": 3},
            {"code": "CHE 231", "title": "Fundamentals of Chemical Engineering-1", "credits": 3},
            {"code": "CHE 232", "title": "Fundamentals of Chemical Engineering-2", "credits": 3},
            {"code": "CHE 233", "title": "Chemical Engineering Thermodynamics-1", "credits": 3},
            {"code": "CHE 234", "title": "Chemical Engineering Thermodynamics-2", "credits": 3},
            {"code": "CHE 242", "title": "Mass and Heat Transfer", "credits": 3},
            {"code": "CHE 321", "title": "Fundamentals of Corrosion", "credits": 3},
            {"code": "CHE 331", "title": "Chemical Reaction Engineering", "credits": 3},
            {"code": "CHE 332", "title": "Modelling and Simulation in Chemical", "credits": 4},
            {"code": "CHE 341", "title": "Fluid Mechanics", "credits": 3},
            {"code": "CHE 342", "title": "Mechanical Unit Operations", "credits": 3},
            {"code": "CHE 345", "title": "Heat Transfer Operations", "credits": 3},
            {"code": "CHE 461", "title": "Chemical Process Industries", "credits": 3},
            {"code": "CHE 481", "title": "Environmental Engineering and Sustainability", "credits": 2},
            {"code": "EEP x82", "title": "Introduction to Electric Circuits and Electrical Machines", "credits": 3},

            # ─── Screenshot 10 ────────────────────────────────────────
            {"code": "CHE 343", "title": "Separation Processes-1", "credits": 3},
            {"code": "CHE 344", "title": "Separation Processes-2", "credits": 3},
            {"code": "CHE 372", "title": "Introduction to Natural Gas Processing", "credits": 3},
            {"code": "CHE 431", "title": "Chemical Process Design", "credits": 3},
            {"code": "CHE 432", "title": "Chemical Plant Design", "credits": 3},
            {"code": "CHE 451", "title": "Chemical Process Control", "credits": 3},
            {"code": "CHE 472", "title": "Fundamentals of Petroleum Refining", "credits": 3},
            {"code": "CHE 401", "title": "Graduation Project-1", "credits": 2},
            {"code": "CHE 402", "title": "Graduation Project-2", "credits": 2},
            {"code": "CHE 3E1", "title": "Elective-1", "credits": 2, "course_type": "ELECTIVE"},
            {"code": "CHE 4E1", "title": "Elective-2", "credits": 2, "course_type": "ELECTIVE"},
            {"code": "CHE 4E2", "title": "Elective-3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CHE 4E3", "title": "Elective-4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CHE 4E4", "title": "Elective-5", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CHE 4E5", "title": "Elective-6", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 11 ────────────────────────────────────────
            {"code": "TEE 211", "title": "Textile Material Science and Engineering", "credits": 4},
            {"code": "TEE 231", "title": "Spinning Engineering-1", "credits": 3},
            {"code": "TEE 221", "title": "Mechanical Drawing with CAD", "credits": 2},
            {"code": "TEE 351", "title": "Application of Statistics in Textiles", "credits": 3},
            {"code": "TEE 321", "title": "Design and Theory of Textile Machinery", "credits": 3},
            {"code": "TEE 241", "title": "Weaving Preparation", "credits": 3},
            {"code": "TEE 341", "title": "Weaving Engineering -1", "credits": 3},
            {"code": "TEE 311", "title": "Textile materials testing and evaluation", "credits": 3},
            {"code": "TEE 332", "title": "Spinning Engineering-2", "credits": 3},
            {"code": "TEE 343", "title": "Knitting Engineering-1", "credits": 3},
            {"code": "TEE 421", "title": "Mechanics of Textile Machinery", "credits": 3},
            {"code": "TEE 451", "title": "Applications of industry 4.0 in textile Industry", "credits": 2},
            {"code": "TEE 411", "title": "Textile Finishing Technology", "credits": 2},
            {"code": "STR x21", "title": "Properties and Testing of Materials-1", "credits": 3},
            {"code": "STR x19", "title": "Structure Engineering-1", "credits": 2},
            {"code": "EEP x56", "title": "Introduction to Power Electronics and Industrial Automation", "credits": 3},
            {"code": "EEP x82", "title": "Introduction to Electric Circuits and Electrical machines", "credits": 3},
            {"code": "MEC x12", "title": "Thermodynamics", "credits": 3},
            {"code": "MEC x34", "title": "Fluid Mechanics and hydraulic Machinery", "credits": 3},

            # ─── Screenshot 12 ────────────────────────────────────────
            {"code": "TEE 331", "title": "Man-made fiber Production and Engineering", "credits": 2},
            {"code": "TEE 342", "title": "Weaving Engineering -2", "credits": 3},
            {"code": "TEE 344", "title": "Garment Engineering and Production", "credits": 3},
            {"code": "TEE 431", "title": "Theoretical Aspects of Yarn Structures and Formations", "credits": 3},
            {"code": "TEE 452", "title": "Sustainable Management and Organization for Textile Mills", "credits": 3},
            {"code": "TEE 422", "title": "Automatic Control and Robotic Application in the Textile Industry", "credits": 3},
            {"code": "TEE 453", "title": "Quality Management and Control in Textile Manufacturing", "credits": 3},
            {"code": "TEE 401", "title": "Graduation Project 1", "credits": 2},
            {"code": "TEE 402", "title": "Graduation Project 2", "credits": 2},
            {"code": "TEE 4E1", "title": "Elective 1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "TEE 4E2", "title": "Elective 2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "TEE 4E3", "title": "Elective 3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "TEE 4E4", "title": "Elective 4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "TEE 4E5", "title": "Elective 5", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 13 ────────────────────────────────────────
            {"code": "NAM 231", "title": "Engineering Materials", "credits": 3},
            {"code": "NAM 281", "title": "Naval Architecture 1", "credits": 3},
            {"code": "NAM 221", "title": "Fluid Mechanics 1", "credits": 3},
            {"code": "NAM 232", "title": "Mechanical Design and Vibration", "credits": 3},
            {"code": "NAM 241", "title": "Marine Power Plants", "credits": 3},
            {"code": "NAM 262", "title": "Ship Construction", "credits": 3},
            {"code": "EEP x81", "title": "Electric Engineering", "credits": 2},
            {"code": "NAM 222", "title": "Fluid Mechanics 2", "credits": 3},
            {"code": "NAM 323", "title": "Marine Hydrodynamics 1", "credits": 3},
            {"code": "NAM 333", "title": "Marine Structures 1", "credits": 3},
            {"code": "NAM 342", "title": "Marine Internal Combustion Engines", "credits": 3},
            {"code": "NAM 346", "title": "Marine Renewable Energy", "credits": 3},
            {"code": "NAM 383", "title": "Ship Design 1", "credits": 3},
            {"code": "NAM 371", "title": "Offshore Engineering 1", "credits": 3},
            {"code": "NAM 382", "title": "Naval Architecture 2", "credits": 3},
            {"code": "NAM 391", "title": "Maritime Statutes and Regulations", "credits": 2},
            {"code": "NAM 3E1", "title": "Elective 1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MEC x12", "title": "Thermodynamics", "credits": 3},

            # ─── Screenshot 14 ────────────────────────────────────────
            {"code": "NAM 334", "title": "Marine Structures 2", "credits": 3},
            {"code": "NAM 484", "title": "Ship Design 2", "credits": 3},
            {"code": "NAM 435", "title": "Marine Structures 3", "credits": 3},
            {"code": "NAM 451", "title": "Computer Applications in the Marine Field", "credits": 3},
            {"code": "NAM 436", "title": "Marine Dynamics", "credits": 3},
            {"code": "NAM 424", "title": "Marine Hydrodynamics 2", "credits": 3},
            {"code": "NAM 464", "title": "Shipbuilding Technology", "credits": 2},
            {"code": "NAM 472", "title": "Offshore Engineering 2", "credits": 3},
            {"code": "NAM 401", "title": "Graduation Project 1", "credits": 2},
            {"code": "NAM 402", "title": "Graduation Project 2", "credits": 2},
            {"code": "NAM 3E2", "title": "Elective -2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "NAM 4E1", "title": "Elective -3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "NAM 4E2", "title": "Elective -4", "credits": 2, "course_type": "ELECTIVE"},
            {"code": "NAM 4E3", "title": "Elective -5", "credits": 2, "course_type": "ELECTIVE"},
            {"code": "NAM 4E4", "title": "Elective -6", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 15 ────────────────────────────────────────
            {"code": "MIE 211", "title": "Principles of Materials Engineering", "credits": 3},
            {"code": "MIE 212", "title": "Manufacturing Properties of Materials", "credits": 3},
            {"code": "MIE 221", "title": "Machining Processes-1", "credits": 3},
            {"code": "MIE 231", "title": "Mechanical Engineering Drawing", "credits": 3},
            {"code": "MIE 241", "title": "Production Quality Control", "credits": 3},
            {"code": "MIE 242", "title": "Engineering Metrology - 1", "credits": 3},
            {"code": "MIE 251", "title": "Management Information System", "credits": 3},
            {"code": "MIE 252", "title": "Cost Analysis & Engineering Economy", "credits": 3},
            {"code": "MIE 311", "title": "Casting & Joining", "credits": 3},
            {"code": "MIE 312", "title": "Solid Mechanics", "credits": 3},
            {"code": "MIE 321", "title": "Machining Processes-2", "credits": 3},
            {"code": "MIE 331", "title": "Machine Design-1", "credits": 3},
            {"code": "MIE 332", "title": "Machine Design-2", "credits": 3},
            {"code": "MIE 351", "title": "Basics of Operations Research", "credits": 3},
            {"code": "EEP x56", "title": "Introduction to Power Electronics & Industrial Automation", "credits": 3},
            {"code": "EEP x82", "title": "Introduction to Electric Circuits & Electrical Machines", "credits": 3},
            {"code": "MEC 345", "title": "Automatic Control", "credits": 3},
            {"code": "MEC x12", "title": "Thermodynamics", "credits": 3},
            {"code": "MEC x34", "title": "Fluid Mechanics and Hydraulic Machinery", "credits": 3},

            # ─── Screenshot 16 ────────────────────────────────────────
            {"code": "MIE 313", "title": "Metal Forming Processes", "credits": 3},
            {"code": "MIE 341", "title": "Engineering Metrology - 2", "credits": 3},
            {"code": "MIE 431", "title": "Mechanical Systems Vibration", "credits": 3},
            {"code": "MIE 451", "title": "Industrial Project Planning & Management", "credits": 3},
            {"code": "MIE 401", "title": "Graduation Project - 1", "credits": 3},
            {"code": "MIE 402", "title": "Graduation Project - 2", "credits": 3},
            {"code": "MIE 4E1", "title": "Elective - 1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MIE 4E2", "title": "Elective - 2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MIE 4E3", "title": "Elective - 3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MIE 4E4", "title": "Elective - 4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MIE 4E5", "title": "Elective - 5", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MIE 4E6", "title": "Elective - 6", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 17 ────────────────────────────────────────
            {"code": "NRE 211", "title": "Atomic Physics", "credits": 3},
            {"code": "NRE 212", "title": "Nuclear Physics", "credits": 3},
            {"code": "NRE 214", "title": "Thermodynamics and Kinetic Theory of Gases", "credits": 3},
            {"code": "NRE 221", "title": "Introduction to Material Science & Engineering", "credits": 3},
            {"code": "NRE 252", "title": "Programing for Nuclear Applications", "credits": 3},
            {"code": "NRE 313", "title": "Neutron Physics", "credits": 3},
            {"code": "NRE 335", "title": "Introduction to Plasma and Fusion Reactors", "credits": 3},
            {"code": "NRE 341", "title": "Radiation Detection and Measurements", "credits": 3},
            {"code": "NRE 342", "title": "Radiation Protection and Shielding", "credits": 3},
            {"code": "NRE 353", "title": "Applied Heat Transfer", "credits": 3},
            {"code": "NRE 354", "title": "Thermal Power Plants", "credits": 3},
            {"code": "NRE 423", "title": "Nuclear Reactor Materials", "credits": 3},
            {"code": "NRE 434", "title": "Automatic Control in Nuclear Reactors", "credits": 2},
            {"code": "EEC 332", "title": "Fundamentals of Electronics", "credits": 3},
            {"code": "EEP x82", "title": "Introduction to Electric Circuits and Electrical Machines", "credits": 3},
            {"code": "EEP 425", "title": "Electric Power Systems and Distribution", "credits": 3},
            {"code": "MEC x34", "title": "Fluid Mechanics and Hydraulic Machinery", "credits": 3},
            {"code": "MEC x42", "title": "Stress Analysis", "credits": 3},

            # ─── Screenshot 18 ────────────────────────────────────────
            {"code": "NRE 412", "title": "Nuclear Power Plants", "credits": 3},
            {"code": "NRE 430", "title": "Physical Analysis of Nuclear Reactor", "credits": 3},
            {"code": "NRE 431", "title": "Nuclear Reactor Kinetics", "credits": 3},
            {"code": "NRE 432", "title": "Reactor Thermal Hydraulics", "credits": 3},
            {"code": "NRE 433", "title": "Nuclear Fuel Cycles", "credits": 3},
            {"code": "NRE 401", "title": "Graduation Project-1", "credits": 2},
            {"code": "NRE 402", "title": "Graduation Project-2", "credits": 2},
            {"code": "NRE 3E1", "title": "Elective 1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "NRE 3E2", "title": "Elective 2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "NRE 4E3", "title": "Elective 3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "NRE 4E4", "title": "Elective 4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "NRE 4E5", "title": "Elective 5", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 19 ────────────────────────────────────────
            {"code": "CSE 211", "title": "Discrete Structures", "credits": 3},
            {"code": "CSE 212", "title": "Probability and Statistics for Computer Engineers", "credits": 3},
            {"code": "CSE 221", "title": "Programming I", "credits": 3},
            {"code": "CSE x22", "title": "Data Structures", "credits": 3},
            {"code": "CSE 231", "title": "Digital Logic Design", "credits": 3},
            {"code": "CSE 232", "title": "Digital Systems Design", "credits": 3},
            {"code": "CSE 271", "title": "Signals and Information Theory", "credits": 3},
            {"code": "CSE 281", "title": "Computer and Society", "credits": 1},
            {"code": "CSE 311", "title": "Numerical and Optimization Methods", "credits": 3},
            {"code": "CSE 321", "title": "Programming II", "credits": 3},
            {"code": "CSE 322", "title": "Data Structures and Algorithms", "credits": 3},
            {"code": "CSE 323", "title": "Programming Languages Paradigms", "credits": 3},
            {"code": "CSE 324", "title": "Design and Analysis of Algorithms", "credits": 3},
            {"code": "CSE 331", "title": "Computer Organization", "credits": 3},
            {"code": "CSE 341", "title": "Fundamentals of Control Systems", "credits": 3},
            {"code": "CSE 361", "title": "Operating Systems", "credits": 3},
            {"code": "CSE 381", "title": "Human Computer Interaction", "credits": 1},
            {"code": "CSE 431", "title": "Computer Networks", "credits": 3},
            {"code": "EEP 215", "title": "Fundamentals of Electrical Engineering", "credits": 3},
            {"code": "EEC 231", "title": "Electronic Circuits and Devices", "credits": 3},

            # ─── Screenshot 20 ────────────────────────────────────────
            {"code": "CSE 332", "title": "Computer Architecture", "credits": 3},
            {"code": "CSE 351", "title": "Introduction to Artificial Intelligence", "credits": 3},
            {"code": "CSE 421", "title": "Software Engineering", "credits": 3},
            {"code": "CSE 441", "title": "Embedded Systems and IoT", "credits": 3},
            {"code": "CSE 461", "title": "Distributed Systems", "credits": 3},
            {"code": "CSE 462", "title": "Security of Computer Systems", "credits": 3},
            {"code": "CSE 471", "title": "Database Systems", "credits": 3},
            {"code": "CSE 401", "title": "Graduation Project I", "credits": 2},
            {"code": "CSE 402", "title": "Graduation Project II", "credits": 2},
            {"code": "CSE 3E1", "title": "Elective 1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CSE 4E1", "title": "Elective 2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CSE 4E2", "title": "Elective 3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CSE 4E3", "title": "Elective 4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CSE 4E4", "title": "Elective 5", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 21 ────────────────────────────────────────
            {"code": "CHE 216", "title": "Principles of Organic Chemistry", "credits": 4},
            {"code": "CHE 226", "title": "Principles of Materials Science and Engineering", "credits": 3},
            {"code": "CHE x21", "title": "Polymer Engineering", "credits": 2},
            {"code": "CHE 327", "title": "Corrosion Engineering", "credits": 3},
            {"code": "MEC 243", "title": "Mechanics of Materials", "credits": 3},
            {"code": "MIE x12", "title": "Non-destructive Testing", "credits": 3},
            {"code": "MEC x46", "title": "Properties and strength of Materials", "credits": 3},
            {"code": "MIE 212", "title": "Manufacturing Properties of Materials", "credits": 3},
            {"code": "MEC x12", "title": "Thermodynamics", "credits": 3},
            {"code": "MEC 347", "title": "Mechanical Design", "credits": 3},
            {"code": "MEC x34", "title": "Fluid Mechanics & Hydraulic Machinery", "credits": 3},
            {"code": "MEC 311", "title": "Heat Transfer", "credits": 3},
            {"code": "MIE 416", "title": "Failure Analysis", "credits": 3},
            {"code": "MSE 312", "title": "Properties of Textile Materials", "credits": 2},
            {"code": "EEP x82", "title": "Introduction to Electric Circuits and Electrical Machines", "credits": 3},
            {"code": "EEP x56", "title": "Introduction to Power Electronics & Industrial Automation", "credits": 3},
            {"code": "MRE x51", "title": "Automatic Control for Mechatronics Systems", "credits": 3},
            {"code": "MSE 313", "title": "Technology of Fibers &Tissues", "credits": 3},

            # ─── Screenshot 22 ────────────────────────────────────────
            {"code": "CHE x65", "title": "Electrochemical Processes", "credits": 3},
            {"code": "MSE 311", "title": "Introduction to Composite Materials", "credits": 3},
            {"code": "MIE 414", "title": "Material Selection", "credits": 3},
            {"code": "MIE 413", "title": "Advanced Forming Processes", "credits": 3},
            {"code": "CHE x82", "title": "Clean Energy process", "credits": 2},
            {"code": "MSE 421", "title": "Industrial Applications of Sustainable Material", "credits": 2},
            {"code": "MSE 401", "title": "Graduation Project-1", "credits": 3},
            {"code": "MSE 402", "title": "Graduation Project-2", "credits": 3},
            {"code": "MSE 3E1", "title": "Elective-1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MSE 4E2", "title": "Elective-2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MSE 4E3", "title": "Elective-3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MSE 4E4", "title": "Elective-4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MSE 4E5", "title": "Elective-5", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 23 ────────────────────────────────────────
            {"code": "CHE 216", "title": "Principles of Organic Chemistry", "credits": 4},
            {"code": "CHE 217", "title": "Fundamentals of Physical Chemistry", "credits": 3},
            {"code": "CHE 226", "title": "Principles of Materials Science and Engineering", "credits": 3},
            {"code": "CHE 236", "title": "Fundamentals of Mass Balance", "credits": 3},
            {"code": "CHE 237", "title": "Fundamentals of Energy Balance", "credits": 3},
            {"code": "CHE 326", "title": "Principles of Polymer Engineering and Science", "credits": 3},
            {"code": "CHE 336", "title": "Applied Thermodynamics", "credits": 2},
            {"code": "CHE 327", "title": "Corrosion Engineering", "credits": 3},
            {"code": "CHE 337", "title": "Kinetics and Reaction Engineering", "credits": 3},
            {"code": "CHE 346", "title": "Separation Processes", "credits": 4},
            {"code": "CHE 347", "title": "Fundamentals of Heat Transfer", "credits": 3},
            {"code": "CHE 357", "title": "Introduction to Natural Gas Engineering", "credits": 3},
            {"code": "CHE 436", "title": "Hazardous Processes and Safety Engineering", "credits": 3},
            {"code": "CHE 456", "title": "Modeling and Simulation", "credits": 3},
            {"code": "EEP 216", "title": "Electric Circuits", "credits": 3},
            {"code": "MEC 216", "title": "Engineering Thermodynamics", "credits": 3},
            {"code": "MEC x36", "title": "Engineering Fluid Mechanics", "credits": 3},

            # ─── Screenshot 24 ────────────────────────────────────────
            {"code": "CHE 356", "title": "Petroleum Refining Engineering", "credits": 3},
            {"code": "CHE 466", "title": "Petrochemical Industries", "credits": 3},
            {"code": "CHE 437", "title": "Process Dynamics and Control", "credits": 3},
            {"code": "CHE 438", "title": "Process Design", "credits": 3},
            {"code": "CHE 457", "title": "Natural Gas Treatment and Purification", "credits": 3},
            {"code": "CHE 458", "title": "Enhanced Oil and gas recovery", "credits": 2},
            {"code": "CHE 459", "title": "Natural Gas Liquefaction", "credits": 3},
            {"code": "GPE 401", "title": "Graduation Project-1", "credits": 3},
            {"code": "GPE 402", "title": "Graduation Project-2", "credits": 3},
            {"code": "CHE 2E1", "title": "Elective-1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CHE 3E2", "title": "Elective-2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CHE 3E3", "title": "Elective-3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CHE 4E4", "title": "Elective-4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CHE 4E5", "title": "Elective-5", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 25 ────────────────────────────────────────
            {"code": "EEC 236", "title": "Electronic Devices and Circuits", "credits": 3},
            {"code": "EEC 246", "title": "Logic Circuits and Micro Processors", "credits": 3},
            {"code": "EEP 216", "title": "Electric Circuits", "credits": 3},
            {"code": "EEP 217", "title": "Electrical Measurements and Instrumentation", "credits": 3},
            {"code": "EEP 226", "title": "Electrical Power Systems", "credits": 3},
            {"code": "EEP 316", "title": "Measuring Systems and Data Acquisition", "credits": 3},
            {"code": "EEP 336", "title": "Electrical Machines", "credits": 3},
            {"code": "EEP 346", "title": "Automatic Control of Electromechanical Systems", "credits": 3},
            {"code": "EEP 356", "title": "Industrial Electronics", "credits": 3},
            {"code": "MEC 216", "title": "Engineering Thermodynamics", "credits": 3},
            {"code": "MEC 236", "title": "Engineering Fluid Mechanics", "credits": 3},
            {"code": "MEC 247", "title": "Fundamentals of Computer Aided Mechanical Drawing", "credits": 2},
            {"code": "MEC 311", "title": "Heat Transfer", "credits": 3},
            {"code": "MEC 321", "title": "Fundamentals of Combustion Engineering", "credits": 2},
            {"code": "MEC 332", "title": "Fluid Mechanics - 2", "credits": 3},
            {"code": "MEC x45", "title": "Strength of materials", "credits": 2},
            {"code": "MEC x47", "title": "Mechanical Design", "credits": 3},
            {"code": "MEC x48", "title": "Dynamics of Machinery", "credits": 3},
            {"code": "MEC x49", "title": "Mechanical Vibrations", "credits": 3},

            # ─── Screenshot 26 ────────────────────────────────────────
            {"code": "EEP 436", "title": "Electromechanical Drives", "credits": 3},
            {"code": "EEP 456", "title": "Industrial Automation", "credits": 3},
            {"code": "MEC 322", "title": "Internal Combustion Engines", "credits": 3},
            {"code": "MEC x13", "title": "Thermal Power Plants", "credits": 3},
            {"code": "MEC x14", "title": "Refrigeration and Air conditioning", "credits": 2},
            {"code": "MEC 433", "title": "Hydraulic Machines", "credits": 3},
            {"code": "EME 401", "title": "Graduation Project-1", "credits": 3},
            {"code": "EME 402", "title": "Graduation Project-2", "credits": 4},
            {"code": "EME 3E1", "title": "Elective-1", "credits": 2, "course_type": "ELECTIVE"},
            {"code": "EME 4E1", "title": "Elective-2", "credits": 2, "course_type": "ELECTIVE"},
            {"code": "EME 4E2", "title": "Elective-3", "credits": 2, "course_type": "ELECTIVE"},
            {"code": "EME 4E3", "title": "Elective-4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EME 4E4", "title": "Elective-5", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EME 4E5", "title": "Elective-6", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 27 ────────────────────────────────────────
            {"code": "CSE 216", "title": "Discrete Structures for Computing", "credits": 2},
            {"code": "CSE 221", "title": "Programming-I", "credits": 3},
            {"code": "CSE 226", "title": "Data Structures-I", "credits": 3},
            {"code": "CSE 237", "title": "Digital Logic Circuits-I", "credits": 3},
            {"code": "CSE 238", "title": "Digital Logic Circuits-II", "credits": 2},
            {"code": "CSE 246", "title": "Control Systems", "credits": 2},
            {"code": "CSE 321", "title": "Programming-II", "credits": 3},
            {"code": "CSE 327", "title": "Data Structures-II", "credits": 2},
            {"code": "CSE 328", "title": "Analysis and Design of Algorithms", "credits": 3},
            {"code": "CSE 331", "title": "Computer Organization", "credits": 3},
            {"code": "CSE 336", "title": "Computer Networks", "credits": 3},
            {"code": "CSE 361", "title": "Operating Systems", "credits": 3},
            {"code": "EEC 216", "title": "Analysis of Electrical Circuits", "credits": 2},
            {"code": "EEC 239", "title": "Electronic Circuit Analysis", "credits": 3},
            {"code": "EEC 271", "title": "Signals and Systems", "credits": 3},
            {"code": "EEC 343", "title": "Microprocessor and Microcontrollers", "credits": 3},
            {"code": "EEC 371", "title": "Digital Signal Processing", "credits": 3},
            {"code": "EEC 381", "title": "Introduction to Communications", "credits": 3},
            {"code": "EEP 218", "title": "Fundamentals of Electric Circuits", "credits": 2},

            # ─── Screenshot 28 ────────────────────────────────────────
            {"code": "CSE 376", "title": "Database Systems", "credits": 3},
            {"code": "CSE 426", "title": "Software Engineering", "credits": 3},
            {"code": "CSE 461", "title": "Distributed Systems", "credits": 3},
            {"code": "CSE 466", "title": "Computer and Network Security", "credits": 3},
            {"code": "EEC 382", "title": "Digital Communications", "credits": 3},
            {"code": "EEC 441", "title": "Embedded Systems", "credits": 3},
            {"code": "CCE 401", "title": "Graduation Project-1", "credits": 3},
            {"code": "CCE 402", "title": "Graduation Project-2", "credits": 3},
            {"code": "CCE 3E1", "title": "Elective-1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CCE 4E1", "title": "Elective-2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CCE 4E2", "title": "Elective-3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CCE 4E3", "title": "Elective-4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CCE 4E4", "title": "Elective-5", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CCE 4E5", "title": "Elective-6", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 29 ────────────────────────────────────────
            {"code": "ARC 214", "title": "Architectural Design 1", "credits": 3},
            {"code": "ARC 291", "title": "History & Theory of Architecture & Planning -1", "credits": 3},
            {"code": "ARC 224", "title": "Building Technology I", "credits": 3},
            {"code": "STR 211", "title": "Structural Analysis I", "credits": 3},
            {"code": "TRE 213", "title": "Construction Surveying", "credits": 3},
            {"code": "ARC 244", "title": "Environment I", "credits": 3},
            {"code": "ARC 215", "title": "Architectural Design 2", "credits": 3},
            {"code": "ARC 225", "title": "Building Technology II", "credits": 3},
            {"code": "STR 223", "title": "Engineering Materials", "credits": 3},
            {"code": "STR 313", "title": "Structural Analysis II", "credits": 3},
            {"code": "ARC 314", "title": "Design Studio I", "credits": 3},
            {"code": "ARC 391", "title": "History & Theory of Architecture & Planning -2", "credits": 3},
            {"code": "STR 331", "title": "Design of R.C. Structures I", "credits": 3},
            {"code": "ARC 354", "title": "Urban Design and Landscape", "credits": 3},
            {"code": "CAE 371", "title": "Environment II", "credits": 3},
            {"code": "ARC 364", "title": "Construction Management I", "credits": 3},
            {"code": "ARC 315", "title": "Design Studio II", "credits": 3},
            {"code": "CAE 372", "title": "Transportation Engineering and Urban Planning", "credits": 3},
            {"code": "STR 351", "title": "Design of Metallic Structures I", "credits": 3},
            {"code": "STR 343", "title": "Soil Mechanics & Design of Foundations and Retaining Structures", "credits": 3},

            # ─── Screenshot 30 ────────────────────────────────────────
            {"code": "CAE 401", "title": "Project I", "credits": 3},
            {"code": "CAE 402", "title": "Project II", "credits": 4},
            {"code": "ARC 491", "title": "Speaking & Writing about the Built Environment", "credits": 3},
            {"code": "ARC 414", "title": "Design Studio III", "credits": 3},
            {"code": "CAE 471", "title": "Environment III", "credits": 2},
            {"code": "CAE 464", "title": "Methods and Equipment for Construction I", "credits": 3},
            {"code": "ARC 465", "title": "Tender I", "credits": 3},
            {"code": "CAE 465", "title": "Methods and Equipment for Construction II", "credits": 3},
            {"code": "CAE 472", "title": "Quality Control and Repair of Structures", "credits": 3},
            {"code": "CAE 4E1", "title": "Elective-2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CAE 4E2", "title": "Elective-3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CAE 4E3", "title": "Elective-4", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 31 ────────────────────────────────────────
            {"code": "EEP 216", "title": "Electric Circuits", "credits": 3},
            {"code": "MEC 216", "title": "Engineering Thermodynamics", "credits": 3},
            {"code": "MEC x36", "title": "Engineering Fluid Mechanics", "credits": 3},
            {"code": "NAM 226", "title": "Marine Hydraulics", "credits": 3},
            {"code": "NAM 227", "title": "Introduction to Oceanography", "credits": 2},
            {"code": "NAM 236", "title": "Marine Structural Analysis-I", "credits": 3},
            {"code": "NAM 256", "title": "Civil and Marine Drawing", "credits": 2},
            {"code": "NAM 266", "title": "Principles of Materials Science for Marine Applications", "credits": 3},
            {"code": "NAM 276", "title": "Introduction to Offshore Engineering", "credits": 2},
            {"code": "NAM 286", "title": "Buoyancy and Stability", "credits": 3},
            {"code": "STR 348", "title": "Marine Foundations", "credits": 3},
            {"code": "NAM 326", "title": "Marine Hydrodynamics", "credits": 3},
            {"code": "NAM 328", "title": "Dynamics of ocean waves", "credits": 3},
            {"code": "NAM 347", "title": "Marine Machinery and Systems", "credits": 3},
            {"code": "TRE 356", "title": "Harbor Planning and Coastal Structures", "credits": 3},
            {"code": "TRE 357", "title": "Sediment Transport and Littoral Processes", "credits": 3},
            {"code": "OCE 3E1", "title": "Elective-1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "OCE 3E2", "title": "Elective-2", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 32 ────────────────────────────────────────
            {"code": "NAM 336", "title": "Marine Structural Analysis-II", "credits": 3},
            {"code": "NAM 438", "title": "Design of Steel Structures", "credits": 2},
            {"code": "NAM 446", "title": "Measurements and Control Systems", "credits": 3},
            {"code": "NAM 366", "title": "Construction of Marine and Offshore Structures", "credits": 3},
            {"code": "NAM 456", "title": "Computer Applications in the Marine Field", "credits": 3},
            {"code": "NAM 470", "title": "Offshore Oil and Gas Production", "credits": 2},
            {"code": "NAM 476", "title": "Design of Offshore Platforms", "credits": 3},
            {"code": "OCE 401", "title": "Project-1", "credits": 3},
            {"code": "OCE 402", "title": "Project-2", "credits": 3},
            {"code": "STR 438", "title": "Design of Reinforced Concrete Structures", "credits": 2},
            {"code": "TRE 456", "title": "Advanced Coastal Structures-I", "credits": 3},
            {"code": "TRE 417", "title": "Surveying in the Marine Field", "credits": 3},
            {"code": "OCE 4E3", "title": "Elective-3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "OCE 4E4", "title": "Elective-4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "OCE 4E5", "title": "Elective-5", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 33 ────────────────────────────────────────
            {"code": "EEC 238", "title": "Electronic Devices", "credits": 3},
            {"code": "BME 251", "title": "Biology", "credits": 3},
            {"code": "MEC 249", "title": "Biomechanics of Solids", "credits": 3},
            {"code": "EEP 216", "title": "Electric Circuits", "credits": 3},
            {"code": "CSE 227", "title": "Programming Fundamentals", "credits": 3},
            {"code": "CSE 236", "title": "Digital Logic Circuits-I", "credits": 3},
            {"code": "MEC 216", "title": "Engineering Thermodynamics", "credits": 3},
            {"code": "MEC x36", "title": "Engineering Fluid Mechanics", "credits": 3},
            {"code": "CHE 218", "title": "Organic Chemistry for Biomedical Engineering", "credits": 3},
            {"code": "EEC 319", "title": "Electrical and Electronic Measurements", "credits": 3},
            {"code": "EEC 346", "title": "Microprocessors and Interfacing", "credits": 3},
            {"code": "EEC 377", "title": "Biomedical Signal Processing", "credits": 3},
            {"code": "EEC 367", "title": "Waves and Acoustics", "credits": 3},
            {"code": "MEC 336", "title": "Biofluid Mechanics", "credits": 3},
            {"code": "BME 351", "title": "Human Anatomy and Physiology", "credits": 3},
            {"code": "BME 392", "title": "Biomaterials", "credits": 3},
            {"code": "BME 391", "title": "Biochemistry for Engineers", "credits": 3},

            # ─── Screenshot 34 ────────────────────────────────────────
            {"code": "BME 477", "title": "Medical Image Processing", "credits": 3},
            {"code": "BME 478", "title": "Bioimaging", "credits": 3},
            {"code": "BME 326", "title": "Biomechanics", "credits": 3},
            {"code": "BME 441", "title": "Tissue Engineering", "credits": 3},
            {"code": "BME 442", "title": "Implant Tissue Interactions.", "credits": 3},
            {"code": "BME 401", "title": "Graduation Project -1", "credits": 3},
            {"code": "BME 402", "title": "Graduation Project -2", "credits": 3},
            {"code": "BME 4E1", "title": "Elective -1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "BME 4E2", "title": "Elective -2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "BME 4E3", "title": "Elective -3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "BME 4E4", "title": "Elective -4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "BME 4E5", "title": "Elective -5", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "BME 4E6", "title": "Elective -6", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 35 ────────────────────────────────────────
            {"code": "STR 216", "title": "Structural Analysis – 1", "credits": 3},
            {"code": "TRE 216", "title": "Construction Surveying", "credits": 3},
            {"code": "STR 217", "title": "Structural Analysis – 2", "credits": 3},
            {"code": "STR 227", "title": "Engineering Material and Stress Analysis", "credits": 3},
            {"code": "SAN 218", "title": "Environmental Microbiology", "credits": 2},
            {"code": "SAN 226", "title": "Environmental Organic Chemistry", "credits": 3},
            {"code": "IRH 216", "title": "Hydraulics for Civil Engineering", "credits": 3},
            {"code": "STR 336", "title": "Design of Reinforced Concrete Structures-I", "credits": 3},
            {"code": "IRH 326", "title": "Fundamentals of Hydrology", "credits": 3},
            {"code": "STR 346", "title": "Soil Mechanics", "credits": 3},
            {"code": "SAN 241", "title": "Thermodynamics for Environmental Engineers", "credits": 2},
            {"code": "IRH 327", "title": "Ground Water Hydrology", "credits": 3},
            {"code": "STR 337", "title": "Design of Reinforced Concrete Structures-II", "credits": 3},
            {"code": "TRE 226", "title": "Construction Engineering Drawings", "credits": 3},
            {"code": "TRE 236", "title": "Geology", "credits": 2},
            {"code": "SAN 341", "title": "Kinetics & Reactor Design", "credits": 3},
            {"code": "STR 411", "title": "Design of steel structures", "credits": 3},
            {"code": "STR 412", "title": "Design of Foundations and Retaining Structures", "credits": 3},
            {"code": "TRE 246", "title": "Transportation Engineering and Urban Planning", "credits": 2},

            # ─── Screenshot 36 ────────────────────────────────────────
            {"code": "SAN 361", "title": "Water Treatment Engineering", "credits": 3},
            {"code": "SAN 381", "title": "Fundamentals of Modelling and Simulation", "credits": 3},
            {"code": "SAN 362", "title": "Wastewater Treatment Engineering", "credits": 3},
            {"code": "SAN 463", "title": "Water Desalination", "credits": 3},
            {"code": "SAN 442", "title": "Bioprocess Design", "credits": 3},
            {"code": "CEE 401", "title": "Graduation Project -1", "credits": 2},
            {"code": "CEE 402", "title": "Graduation Project -2", "credits": 3},
            {"code": "CEE 4E1", "title": "Elective 1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CEE 4E2", "title": "Elective 2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CEE 4E3", "title": "Elective 3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CEE 4E4", "title": "Elective 4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "CEE 4E5", "title": "Elective 5", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 37 ────────────────────────────────────────
            {"code": "CSE 226", "title": "Programming and Problem Solving", "credits": 3},
            {"code": "CSE 326", "title": "Object-Oriented Computer Programming", "credits": 3},
            {"code": "EEC 237", "title": "Electronics for Instruments", "credits": 2},
            {"code": "EEC 246", "title": "Logic Circuits and Micro Processors Applications", "credits": 3},
            {"code": "EEC 486", "title": "Industrial communication and Network systems", "credits": 2},
            {"code": "EEP 216", "title": "Electric Circuits", "credits": 3},
            {"code": "EEP 218", "title": "Electrical and Digital Measurements", "credits": 2},
            {"code": "EEP 317", "title": "Microcontroller Engineering – 1", "credits": 3},
            {"code": "EEP 321", "title": "Industrial Automation 1", "credits": 3},
            {"code": "EEP 337", "title": "Electrical Machines for Mechatronics", "credits": 2},
            {"code": "EEP 357", "title": "Power Electronics and Motor Drives 1", "credits": 3},
            {"code": "MEC 216", "title": "Engineering Thermodynamics", "credits": 3},
            {"code": "MEC x36", "title": "Engineering Fluid Mechanics", "credits": 3},
            {"code": "MEC 242", "title": "Computer Aided Mechanical Drawing", "credits": 3},
            {"code": "MEC 248", "title": "Mechanics of Machinery", "credits": 3},
            {"code": "MEC 346", "title": "Properties and Strength of Materials", "credits": 3},
            {"code": "MEC 347", "title": "Mechanical Design", "credits": 3},
            {"code": "MRE 251", "title": "Automatic Control for Mechatronics Systems", "credits": 3},
            {"code": "MRE 351", "title": "Introduction to Mechatronic Systems", "credits": 3},

            # ─── Screenshot 38 ────────────────────────────────────────
            {"code": "MEC 431", "title": "Hydraulic and Pneumatic Systems", "credits": 3},
            {"code": "MRE 352", "title": "Modern Control; Theory and Systems", "credits": 3},
            {"code": "MRE 353", "title": "Design of Mechatronic Systems", "credits": 3},
            {"code": "MRE 361", "title": "Industrial Robotics", "credits": 3},
            {"code": "MRE 458", "title": "Artificial Intelligence in Mechatronics", "credits": 2},
            {"code": "MRE 401", "title": "Graduation Project 1", "credits": 2},
            {"code": "MRE 402", "title": "Graduation Project 2", "credits": 3},
            {"code": "MRE 4E1", "title": "Elective 1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MRE 4E2", "title": "Elective 2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MRE 4E3", "title": "Elective 3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MRE 4E4", "title": "Elective 4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MRE 4E5", "title": "Elective 5", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MRE 4E6", "title": "Elective 6", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MRE 4E7", "title": "Elective 7", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 39 ────────────────────────────────────────
            {"code": "MAE 211", "title": "Introduction to Mechanical and Aerospace Engineering", "credits": 3},
            {"code": "MAE 232", "title": "Aerodynamics", "credits": 3},
            {"code": "MAE 241", "title": "Computer-Aided Analyses for Aeromechanical Design", "credits": 3},
            {"code": "MAE 311", "title": "Energy and Propulsion", "credits": 2},
            {"code": "MAE 321", "title": "System dynamics and modeling", "credits": 3},
            {"code": "MAE 322", "title": "Modern Control of Aeromechanical Systems", "credits": 3},
            {"code": "MAE 323", "title": "Aircraft Performance", "credits": 3},
            {"code": "MAE 361", "title": "Numerical Methods for Mechanical and Aerospace Engineering", "credits": 3},
            {"code": "MEC 216", "title": "Engineering Thermodynamics", "credits": 3},
            {"code": "MEC 236", "title": "Engineering Fluid Mechanics", "credits": 3},
            {"code": "MEC 248", "title": "Dynamics of Machinery", "credits": 3},
            {"code": "MEC 311", "title": "Heat Transfer", "credits": 3},
            {"code": "MEC 343", "title": "Mechanical Vibrations", "credits": 3},
            {"code": "MEC 346", "title": "Properties and Strength of Materials", "credits": 3},
            {"code": "MEC 347", "title": "Mechanical Design", "credits": 3},
            {"code": "EEP 216", "title": "Electric Circuits", "credits": 3},
            {"code": "EEP 218", "title": "Electrical and Digital Measurements", "credits": 3},
            {"code": "EEP 337", "title": "Electrical Machines for Mechatronics Systems", "credits": 2},

            # ─── Screenshot 40 ────────────────────────────────────────
            {"code": "MAE 332", "title": "Compressible flow", "credits": 3},
            {"code": "MAE 334", "title": "Aircraft Propulsion", "credits": 3},
            {"code": "MAE 342", "title": "Aircraft Structural Design", "credits": 3},
            {"code": "MAE 344", "title": "Computer-Aided Design of Mechanical Systems", "credits": 3},
            {"code": "MAE 421", "title": "Flight Dynamics", "credits": 3},
            {"code": "MAE 431", "title": "Principe of Turbomachinery", "credits": 3},
            {"code": "MAE 451", "title": "Astronautics", "credits": 3},
            {"code": "MAE 401", "title": "Graduation Project 1", "credits": 2},
            {"code": "MAE 402", "title": "Graduation Project 2", "credits": 3},
            {"code": "MAE 4E1", "title": "Elective 1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MAE 4E2", "title": "Elective 2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MAE 4E3", "title": "Elective 3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MAE 4E4", "title": "Elective 4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MAE 4E5", "title": "Elective 5", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "MAE 4E6", "title": "Elective 6", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 41 ────────────────────────────────────────
            {"code": "EEC 232", "title": "Modern Physics", "credits": 3},
            {"code": "EEC 233", "title": "Physics of Semiconductors", "credits": 3},
            {"code": "EEC 234", "title": "Electronic Circuit Design", "credits": 3},
            {"code": "EEC 235", "title": "Materials Science for Engineers", "credits": 3},
            {"code": "EEC 242", "title": "Digital Logic Circuits", "credits": 3},
            {"code": "EEC 261", "title": "Electromagnetic Fields and Waves", "credits": 3},
            {"code": "EEC 271", "title": "Signals and Systems", "credits": 3},
            {"code": "EEC 272", "title": "Control System Theory and Design", "credits": 3},
            {"code": "EEC 331", "title": "Introduction to Photonics", "credits": 3},
            {"code": "EEC 334", "title": "Analog Integrated Circuit Design", "credits": 3},
            {"code": "EEC 335", "title": "Solid State Devices", "credits": 3},
            {"code": "EEC 336", "title": "Fundamentals of Nanomaterials and Nanotechnology", "credits": 3},
            {"code": "EEC 337", "title": "Micro/Nano Fabrication Techniques", "credits": 3},
            {"code": "EEC 383", "title": "Communication Theory and Systems", "credits": 3},
            {"code": "CSE 221", "title": "Programming-I", "credits": 3},
            {"code": "CSE 337", "title": "Computer Architecture and Design", "credits": 3},
            {"code": "EEP 216", "title": "Electric Circuits", "credits": 3},
            {"code": "MEC 314", "title": "Thermo-fluids for Nanoelectronics", "credits": 3},

            # ─── Screenshot 42 ────────────────────────────────────────
            {"code": "EEC 338", "title": "Nanophotonics", "credits": 3},
            {"code": "EEC 344", "title": "MEMS Design and Fabrication", "credits": 3},
            {"code": "EEC 432", "title": "Modeling of Nanodevices", "credits": 3},
            {"code": "EEC 433", "title": "Photovoltaics and Photonic Devices", "credits": 3},
            {"code": "EEC 434", "title": "ASIC and FPGA Design", "credits": 3},
            {"code": "EEC 442", "title": "Embedded System Design", "credits": 3},
            {"code": "EEN 401", "title": "Graduation Project-1", "credits": 3},
            {"code": "EEN 402", "title": "Graduation Project-2", "credits": 3},
            {"code": "EEN 3E1", "title": "Elective-1", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EEN 4E1", "title": "Elective-2", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EEN 4E2", "title": "Elective-3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EEN 4E3", "title": "Elective-4", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EEN 4E4", "title": "Elective-5", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "EEN 4E5", "title": "Elective-6", "credits": 3, "course_type": "ELECTIVE"},

            # ─── Screenshot 43 ────────────────────────────────────────
            {"code": "ARC 217", "title": "Design -1: Human Comfort", "credits": 4},
            {"code": "ARC 218", "title": "Design -2: Integration & Performance", "credits": 4},
            {"code": "ARC 237", "title": "Building Construction-1", "credits": 3},
            {"code": "ARC 238", "title": "Building Construction-2", "credits": 3},
            {"code": "ARC 248", "title": "Computer Applications in Architecture (BIM)", "credits": 3},
            {"code": "ARC 249", "title": "Communication in Architecture", "credits": 2},
            {"code": "ARC 271", "title": "Introduction to Heritage", "credits": 2},
            {"code": "ARC 281", "title": "Environmental Studies", "credits": 2},
            {"code": "ARC 282", "title": "Resilient & Smart Environments", "credits": 2},
            {"code": "ARC 291", "title": "History & Theory of Architecture & Planning-1", "credits": 3},
            {"code": "RSA 291", "title": "Site Analysis & Surveying", "credits": 3},
            {"code": "STR 214", "title": "Structural Analysis", "credits": 3},
            {"code": "ARC 317", "title": "Design -3: Context, Culture & Execution", "credits": 4},
            {"code": "ARC 337", "title": "Execution Design", "credits": 3},
            {"code": "ARC 357", "title": "Urban Design & Landscape", "credits": 3},
            {"code": "ARC 391", "title": "History & Theory of Architecture & Planning-2", "credits": 3},
            {"code": "RSA 391", "title": "MEP Systems", "credits": 3},
            {"code": "STR 333", "title": "Concrete & Steel Structures", "credits": 3},
            {"code": "STR 343", "title": "Soil Mechanics & Properties of Materials", "credits": 3},
            {"code": "ARC 491", "title": "Speaking & Writing about the Built Environment", "credits": 3},

            # ─── Screenshot 44 ────────────────────────────────────────
            {"code": "RSA 401", "title": "Graduation Project Thesis", "credits": 3},
            {"code": "RSA 402", "title": "Graduation Project", "credits": 6},
            {"code": "ARC 3E7", "title": "Elective-1 (Design Studio-1)", "credits": 4, "course_type": "ELECTIVE"},
            {"code": "RSA 3E1", "title": "Elective-2", "credits": 2, "course_type": "ELECTIVE"},
            {"code": "RSA 3E2", "title": "Elective-3", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "ARC 4E7", "title": "Elective-4 (Design Studio-2)", "credits": 4, "course_type": "ELECTIVE"},
            {"code": "RSA 4E1", "title": "Elective-5", "credits": 2, "course_type": "ELECTIVE"},
            {"code": "RSA 4E2", "title": "Elective-6", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "RSA 4E3", "title": "Elective-7", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "RSA 4E4", "title": "Elective-8", "credits": 3, "course_type": "ELECTIVE"},
            {"code": "RSA 4E5", "title": "Elective-9", "credits": 3, "course_type": "ELECTIVE"},
        ]

        

        self.stdout.write("Creating Courses...")
        
        for course_data in courses_data:
            # Extract the department code prefix (e.g., 'STR' from 'STR 211')
            dept_code = course_data["code"].split(" ")[0]
            
            # Map course to existing department
            department = Department.objects.filter(code=dept_code).first()
            
            if not department:
                self.stdout.write(self.style.WARNING(f"Department {dept_code} not found. Skipping {course_data['code']}"))
                continue

            # Check if this dictionary has an explicit course_type. If not, default to CORE
            c_type = course_data.get("course_type", "CORE")

            Course.objects.update_or_create(
                code=course_data["code"],
                defaults={
                    "title": course_data["title"],
                    "credits": course_data["credits"],
                    "course_type": c_type,
                    "department": department
                }
            )
            
        self.stdout.write(self.style.SUCCESS(f" Successfully loaded courses into the database!"))