# Generated by Django 6.0.3 on 2026-04-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='program_type',
            field=models.CharField(choices=[('GSP', 'General Scientific Program'), ('SSP', 'Specialised Scientific Program')], default='GENERAL', max_length=3),
            preserve_default=False,
        ),
    ]
