# Generated by Django 6.0.3 on 2026-04-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_discipline_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_rank',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('SPECIALIZED', 'Specialized')], default='BASIC', max_length=12),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective')], default='CORE', max_length=10),
        ),
    ]
