# Generated by Django 6.0.3 on 2026-04-10 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_course_course_rank_course_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_rank',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
    ]
