# Generated by Django 6.0.3 on 2026-04-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_course_course_rank_remove_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective')], default='CORE', max_length=10),
        ),
    ]
