# Generated by Django 6.0.3 on 2026-04-14 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_room'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={},
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='program_type',
            field=models.CharField(choices=[('GSP', 'General Specialization Program'), ('SSP', 'Specific Specialization Program')], max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('LECTURE', 'Lecture Hall'), ('LAB', 'Laboratory'), ('SEMINAR', 'Seminar Room')], max_length=10),
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_level', models.PositiveSmallIntegerField()),
                ('number', models.PositiveSmallIntegerField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academics.discipline')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academics.term')),
            ],
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_classes', to='users.teacherprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.course')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.term')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_classes', to='academics.studygroup')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studygroup',
            constraint=models.UniqueConstraint(fields=('discipline', 'term', 'year_level', 'number'), name='unique_study_group'),
        ),
        migrations.AddConstraint(
            model_name='courseclass',
            constraint=models.UniqueConstraint(fields=('course', 'term', 'group'), name='unique_course_term_group'),
        ),
    ]
