# Generated by Django 6.0.3 on 2026-04-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_term_options_alter_course_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lab_sessions',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='lec_sessions',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='tut_sessions',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
