# Generated by Django 6.0.3 on 2026-07-05 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_course_lab_sessions_course_lec_sessions_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseclass',
            name='unique_course_term_group',
        ),
        migrations.AlterField(
            model_name='discipline',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='discipline', to='academics.department'),
        ),
        migrations.AddConstraint(
            model_name='courseclass',
            constraint=models.UniqueConstraint(fields=('course', 'group'), name='unique_course_group'),
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='term',
        ),
    ]
