# Generated by Django 6.0.3 on 2026-07-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_courseclass_unique_course_term_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
