# Generated by Django 6.0.3 on 2026-07-12 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_courseclass_deleted_at_courseclass_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseclass',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='is_active',
        ),
    ]
