# Generated by Django 6.0.7 on 2026-07-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_remove_courseclass_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='season',
            field=models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], max_length=10, null=True),
        ),
    ]
