# Generated by Django 6.0.7 on 2026-07-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_auto_20260727_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
