# Generated by Django 6.0.7 on 2026-07-30 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_studygroup_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisite_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks_courses', to='academics.course')),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_requirements', to='academics.course')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target_course', 'prerequisite_course'), name='unique_prerequisite_mapping')],
            },
        ),
        migrations.CreateModel(
            name='CurriculumBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_level', models.PositiveSmallIntegerField(help_text='e.g., 1, 2, 3, 4')),
                ('season', models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], max_length=10)),
                ('is_mandatory', models.BooleanField(default=True, help_text='True for core courses, False for electives.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='academics.course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='academics.discipline')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('discipline', 'course', 'year_level', 'season'), name='unique_blueprint_course_per_semester')],
            },
        ),
    ]
