# Generated by Django 6.0.7 on 2026-08-03 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_courseprerequisite_curriculumblueprint'),
        ('users', '0002_alter_baseuser_managers_studentprofile_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='coordinator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_classes', to='users.teacherprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_classes', to='academics.studygroup'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='academics.department'),
        ),
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='academics.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academics.discipline'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academics.term'),
        ),
    ]
