# Generated by Django 6.0.7 on 2026-08-05 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_course_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_classes', to='academics.studygroup'),
        ),
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='academics.department'),
        ),
        migrations.AlterField(
            model_name='term',
            name='season',
            field=models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], max_length=10),
        ),
    ]
