# Generated by Django 6.0.7 on 2026-08-06 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_alter_courseclass_group_alter_room_department_and_more'),
        ('users', '0002_alter_baseuser_managers_studentprofile_deleted_at_and_more'),
    ]

    operations = [
        
    ]
