# Generated by Django 6.0.7 on 2026-08-06 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_alter_courseclass_coordinator'),
        ('users', '0002_alter_baseuser_managers_studentprofile_deleted_at_and_more'),
    ]

    operations = [
        
        
    ]
