# Generated by Django 6.0.7 on 2026-08-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_alter_courseclass_coordinator'),
        ('users', '0002_alter_baseuser_managers_studentprofile_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_classes', to='users.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_classes', to='academics.studygroup'),
            preserve_default=False,
        ),
    ]
