# Generated by Django 6.0.7 on 2026-09-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_alter_courseclass_coordinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Inherits from StudyGroup on creation, but can be overridden later.', null=True),
        ),
    ]
