# Generated by Django 6.0.7 on 2026-09-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_backfill_courseclass_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Inherits from StudyGroup on creation, but can be overridden later.'),
        ),
    ]
