# Generated by Django 6.0.7 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_alter_courseclass_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='schedule_dirty',
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True when a solver-relevant input (currently: coordinator) changed "
                    "after this class was already scheduled, so its existing sessions no "
                    "longer reflect the intended constraints. Cleared once the cohort is "
                    "(re)scheduled."
                ),
            ),
        ),
    ]
