# Generated by Django 6.0.7 on 2026-09-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_courseclass_schedule_dirty'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='seats_taken',
            field=models.PositiveIntegerField(default=0, help_text="Denormalized ENROLLED count, kept in sync only by EnrollmentService's atomic reserve/release. Don't write to this field anywhere else."),
        ),
    ]